name: dotnet-build-containerize-test-pipeline

permissions:
    contents: read
    packages: write

on:
  push:
    branches:
      - main

  workflow_dispatch:  

jobs:
   
  call-reusable-workflow:
     uses: mitzenjeremywoo/gha-core/.github/workflows/dotnet-build-containerize.yaml@main
    #  with: 
    #    environment: "dev"
