name: Hello World Workflow

on:
  push:
    branches:
      - main

  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout self repo
        uses: actions/checkout@v4

      - name: Checkout gha core
        uses: actions/checkout@v4
        with:
          repository: mitzenjeremywoo/gha-core
          path: gha-core
          token: ${{ secrets.GITHUB_TOKEN }}  # or PAT if private

      - name: Say hello
        run: ls -al -R ${{ github.workspace }}

      - name: Run reusable workflow locally
        uses: ./test.yaml
        with:
          environment: "dev"
      
      # ./gha-core-test-template/gha-core/build/dotnet.yaml
  # call-reusable-workflow:
  #    uses: ./gha-core-test-template/gha-core/build/dotnet.yaml

  